version: "3.3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn ipt_techno_site.wsgi -b 0.0.0.0:8000
    environment:
      - USE_HEROKU_POSTGRES=False
      - ENVIRONMENT=development
      - DEBUG=True
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - .:/code
    ports:
      - 80:8000
      - 443:8000
    depends_on:
      - db
volumes:
  postgres_data:
