# Generated by Django 3.1.2 on 2020-11-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201025_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='section_number',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
