# Generated by Django 3.1.2 on 2020-10-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docpage',
            name='files',
            field=models.ManyToManyField(blank=True, to='documents.Document'),
        ),
    ]
